Feature/10647 aks pipeline access
nhs-digital-gp-it-futures/platform-helm pull request #143
Opened 2020-12-09 16:32 UTC by gavinwakeley1

Task: AB#10647
Story: AB#10643

2020-12-09 16:35 UTC, PhysicsJon requested changes
Just the end of file newlines

2020-12-09 16:35 UTC, PhysicsJon commented on azure-pipelines.yml
> +          az aks update -n gpitfutures-development-aks -g gpitfutures-development-rg-aks --api-server-authorized-ip-ranges "$ipRange" > /dev/null
eof newline

2020-12-09 16:35 UTC, PhysicsJon commented on housekeeping/azure-pipelines.yml
> +        inlineScript: az storage account update --resource-group gpitfutures-development-rg-sa --name gpitfuturesdevelopment --default-action Deny > /dev/null
eof newline

2020-12-10 08:46 UTC, gavinwakeley1 commented on housekeeping/azure-pipelines.yml
> +        inlineScript: az storage account update --resource-group gpitfutures-development-rg-sa --name gpitfuturesdevelopment --default-action Deny > /dev/null
done

2020-12-10 08:46 UTC, gavinwakeley1 commented on azure-pipelines.yml
> +          az aks update -n gpitfutures-development-aks -g gpitfutures-development-rg-aks --api-server-authorized-ip-ranges "$ipRange" > /dev/null
done

2020-12-10 08:51 UTC, PhysicsJon approved these changes

2020-12-10 11:45 UTC, merged